common:
  seed: 42
  input_pkl: '/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/experiment1_user_induced_DL/induced_DL/kg_processing/kg.pkl'
  out: './'
  verbose: true
  run_kg_prep: false
  run_training: true
  run_evaluation: false

model:
  name: "DistMult"               
  emb_dim: 200
  margin: 1                  

sampler:
  name: 'Mixed'
  n_neg: 5

optimizer:
  name: "Adam"
  params:
    lr: 0.001
    weight_decay: 0.001                        

training:
  max_epochs: 1000              
  batch_size: 4096     
  eval_interval: 10
  eval_batch_size: 32
