name: drug_repurposing_benchmark  
channels:
  - defaults
  - conda-forge
  - pytorch
  - pyg
  - nvidia # CUDA
dependencies:
  - python=3.10
  - pandas
  - pyyaml
  - numpy
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit  # CUDA
  - tqdm
  - matplotlib
  - ignite
  - pyg
  - pip
  - pip:
      - torchkge
