common:
  seed: 42
  input_csv: "/home/galadriel/dr_benchmark/knowledge_graph/shep_kg_without_orphan_treatments.csv"
  out: "/home/galadriel/dr_benchmark/experiment1_user_induced_DL/induced_DL/kg_processing/"
  run_kg_prep: true
  run_training: false
  run_evaluation: false
  plot_training_metrics: false

clean_kg:   
  remove_duplicates_triplets: true 

  make_directed: true
  make_directed_params: 
    - "disease_disease"
    - "drug_drug"
    - "protein_protein"

  check_synonymous_antisynonymous: false 

  permute_kg: false

  clean_train_set: false

  mixed_test: true
