common:
  seed: 42
  input_csv: "$WORK/knowledge_graph/shep_kg_without_orphan_treatments.csv"
  out: "$WORK/DL1experiment/withoutDL1/kg_processing/"
  run_kg_prep: true
  run_training: false
  run_evaluation: false

clean_kg:   
  remove_duplicates_triplets: true 

  make_directed: true
  make_directed_params: 
    - "disease_disease"
    - "drug_drug"
    - "protein_protein"

  check_DL1: true 
  check_DL1_params:
    theta1: 0.8
    theta2: 0.8

  permute_kg: false

  clean_train_set: true

  mixed_test: true
