common:
  seed: 42
  input_csv: "/home/galadriel/dr_benchmark/knowledge_graph/shep_kg_without_orphan_treatments.csv"
  out: "/home/galadriel/dr_benchmark/experiment1_user_induced_DL/no_directed/kg_processing/"
  run_kg_prep: true
  run_training: false
  run_evaluation: false

clean_kg:   
  remove_duplicates_triplets: true 

  make_directed: false

  check_synonymous_antisynonymous: true 
  check_synonymous_antisynonymous_params:
    theta1: 0.8
    theta2: 0.8

  permute_kg: false

  clean_train_set: true

  mixed_test: true
