common:
  seed: 42
  input_pkl: '/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/experiment2_structural_DL/kg_processing/kg.pkl'
  out: './'
  verbose: true
  run_kg_prep: false
  run_training: true
  run_evaluation: true
  plot_training_metrics: true

model:
  name: "ANALOGY"               
  emb_dim: 200
  margin: 1                  

sampler:
  name: 'Mixed'
  n_neg: 5

optimizer:
  name: "Adam"
  params:
    lr: 0.001
    weight_decay: 0.001                        

training:
  max_epochs: 1000              
  batch_size: 4096     
  eval_interval: 20
  eval_batch_size: 64
  patience: 20

evaluation:
  made_directed_relations: ["drug_drug", "disease_disease", "protein_protein", "drug_drug_inv", "disease_disease_inv", "protein_protein_inv"]
  target_relations: ["indication"]
