common:
  seed: 42
  # input_csv: "/home/galadriel/dr_benchmark/knowledge_graph/shep_kg_without_orphan_treatments.csv"
  input_pkl: '/home/galadriel/dr_benchmark/processed_kgs/minimal_kg/mixed_test/unpermuted/kg.pkl'
  out: "./"
  verbose: true
  run_kg_prep: false
  run_training: true
  run_evaluation: false

model:
  name: "TransEModelWithGCN"               
  emb_dim: 200
  margin: 1                  

sampler:
  name: 'Mixed'

optimizer:
  name: "Adam"
  params:
    weight_decay: 0.001                        

# lr_scheduler:
#   type: "CosineAnnealingWarmRestarts"
#   params:
#     T_0: 10
#     T_mult: 2         

training:
  max_epochs: 2000              
  patience: 20            
  batch_size: 2048     
  eval_interval: 10
  eval_batch_size: 32
