common:
  seed: 42
  input_csv: "/home/galadriel/dr_benchmark/knowledge_graph/shep_kg_without_orphan_treatments.csv"
  out: "/home/galadriel/dr_benchmark/experiment2_structural_DL/kg_processing/"
  run_kg_prep: true
  run_training: false
  run_evaluation: false
  plot_training_metrics: false

clean_kg:   
  remove_duplicates_triplets: true 

  make_directed: true
  make_directed_params: 
    - "disease_disease"
    - "drug_drug"
    - "protein_protein"

  check_synonymous_antisynonymous: true
  check_synonymous_antisynonymous_params:
    theta1: 0.8
    theta2: 0.8

  permute_kg: true
  permute_kg_params:
    - 'indication'

  clean_train_set: true

  mixed_test: true
